# After changing this file, check it on:
# http://lint.travis-ci.org/
sudo: false
cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip
    - $HOME/.theano
    - $HOME/miniconda2/envs/pyenv


language: python
python:
  - "2.7"
  - "3.3"

# command to install dependencies
before_install:
  - chmod +x ./.travis/travis_before_install.sh
  - ./.travis/travis_before_install.sh

addons:
  apt_packages:
   - texlive-latex-recommended
   - texlive-latex-extra
   - texlive-fonts-recommended
   - dvipng

install:
  - chmod +x ./.travis/travis_install.sh
  - ./.travis/travis_install.sh

# command to run tests
env:
  - PART="theano/tests/test_flake8.py" DOC=1

script:
  - export THEANO_FLAGS=$THEANO_FLAGS,warn.ignore_bug_before=all,on_opt_error=raise,on_shape_error=raise,gcc.cxxflags=-pipe
  - python --version
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  # Move out of Theano so the import will use the installed version
  - cd ..
  # Move to the path of the installed version
  - cd $(python -c 'import theano; import os; print(os.path.split(theano.__file__)[0])')
  - echo "$PART"
  - cd -; cd Theano
  - python -c 'import theano; print(theano.config.__str__(print_doc=False))'
  - python -c 'import theano; assert(theano.config.blas.ldflags != "")'
  - theano-nose -v $PART
  - if [[ $DOC == "1" ]]; then python doc/scripts/docgen.py --nopdf --check; fi
  - if [[ $DOC == "1" ]]; then python doc/scripts/docgen.py --test --check; fi

after_failure:
  - cat /home/travis/.pip/pip.log
